version: 0.2
phases:
  install:
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - package.json
    - .next/**/*
