version: 0.2

phases:
  install:
    commands:
      - echo "Installing source NPM dependencies..."

  build:
    commands:
      - echo "Building the app..."

artifacts:
  files:
    - "**/*"
  base-directory: ""
