import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
// import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      {/* <head>
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </head> */}
      <body className={inter.className}>
        <main>{children}</main>
        {/* <Toaster /> */}
        <Footer />
      </body>
    </html>
  );
}
